### ISSUE TITLE
It's better to give more detailed howto things.

### ISSUE THREAD

**Issue by nagexiucai** [luxe/unilang#354]
such as principle, structure, build-steps.
from its literature, now i regard it as a unified syntax parser?

**Comment by luxe** [comment]
thank you for the comment!!!

for principle, we added "summary" and "design" to the readme.
for structure, we added info about "schema" and a pipeline of the tools involved.
for build-steps, there is a section building now.

> from its literature, now i regard it as a unified syntax parser?

It's like a GUI for encoding information into a giant structured format, and then converting that information into some other language's source code.  

Hope all is well with you.
