### ISSUE TITLE
Relationship to Deepin's unilang

### ISSUE THREAD

**Issue by markusbkk** [luxe/unilang#468]
Just curious. Is there any relationship to [unilang](https://github.com/linuxdeepin/unilang) by Deepin, or are these two projects just coincidentally named the same way?

**Comment by luxe** [comment]
These projects are not related, but it appears we have similar goals.  I'll have to try Deepin's language and UI to see where our ideas overlap.  Thank you for showing me the project. Its funny we picked the same names, but maybe it was a good pick since the projects also seem similar. XD
